name: Workflow Dispatcher
description: Maintain workflow state and triggers a workflow if everything satisfies
inputs:
  host:
    description: application host url ex. "https://example.com"
    required: true
  task:
    description: provide remaining route path ex. manifest or vote
    required: true
  group:
    description: provide anything name you want to group the workflow status ex. ci
    required: true
  token:
    description: provide the pat or token for further request ex. {{ secrets.GITHUB_TOKEN }}
    required: true
  watch:
    description: provide the workflow names using commas ex. "ci-product,ci-users"
    required: false
  finished:
    description: provide wherther workflow has finised ex. true or false
    required: false
  workflow:
    description: provide workflow name ex. custom-workflow-ci
    required: false
  workflowRef:
    description: provide workflow branch ref ex. "main"
    required: false
  workflowId:
    description: provide workflow id or workflow file name ex. ci.yml
    required: false
  repository:
    description: provide the repository path ex. username/repository
    required: false
runs:
  using: "node16"
  main: "main.js"
branding:
  icon: terminal
  color: gray-dark
